#!/usr/bin/env node
/**
 * burooj.design token compiler.
 *
 * Reads tokens.json (DTCG format) and produces:
 *   build/tokens.css         - CSS custom properties
 *   build/tailwind.tokens.js - Tailwind config extension
 *
 * Self-contained: no external dependencies. Run with `node compile.mjs`.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TOKENS_PATH = join(__dirname, 'tokens.json')
const BUILD_DIR = join(__dirname, 'build')

// ── Token tree walker ───────────────────────────────────────────────────────

function walkTokens(obj, path = [], results = []) {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue
    const currentPath = [...path, key]
    if (value && typeof value === 'object' && '$value' in value) {
      results.push({ path: currentPath, value: value.$value, type: value.$type })
    } else if (value && typeof value === 'object') {
      walkTokens(value, currentPath, results)
    }
  }
  return results
}

// ── CSS custom property generation ──────────────────────────────────────────

function tokenToCssValue(value, type) {
  if (type === 'color' || type === 'dimension') {
    return String(value)
  }
  if (type === 'shadow') {
    const s = value
    return `${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`
  }
  if (type === 'typography') {
    // Typography is composite; expose individual sub-properties instead.
    return null
  }
  return String(value)
}

function generateCss(tokens) {
  const lines = [
    '/* Auto-generated by burooj.design/compile.mjs. Do not edit. */',
    '/* Source: tokens.json (DTCG format) */',
    '',
    ':root {'
  ]

  for (const token of tokens) {
    const name = `--${token.path.join('-')}`

    if (token.type === 'typography') {
      // Flatten composite typography into individual properties.
      const t = token.value
      const prefix = token.path.join('-')
      if (t.fontFamily) lines.push(`  --${prefix}-font-family: ${t.fontFamily};`)
      if (t.fontSize) lines.push(`  --${prefix}-font-size: ${t.fontSize};`)
      if (t.fontWeight) lines.push(`  --${prefix}-font-weight: ${t.fontWeight};`)
      if (t.lineHeight) lines.push(`  --${prefix}-line-height: ${t.lineHeight};`)
      if (t.letterSpacing) lines.push(`  --${prefix}-letter-spacing: ${t.letterSpacing};`)
    } else {
      const cssValue = tokenToCssValue(token.value, token.type)
      if (cssValue !== null) {
        lines.push(`  ${name}: ${cssValue};`)
      }
    }
  }

  lines.push('}', '')
  return lines.join('\n')
}

// ── Tailwind config generation ──────────────────────────────────────────────

function generateTailwindConfig(tokens) {
  const colors = {}
  const spacing = {}
  const borderRadius = {}
  const boxShadow = {}
  const fontSize = {}

  for (const token of tokens) {
    const varName = `--${token.path.join('-')}`
    const cssVar = `var(${varName})`

    if (token.type === 'color') {
      setNested(colors, token.path.slice(1), cssVar)
    } else if (token.path[0] === 'spacing' && token.type === 'dimension') {
      spacing[token.path[token.path.length - 1]] = cssVar
    } else if (token.path[0] === 'radius' && token.type === 'dimension') {
      borderRadius[token.path[token.path.length - 1]] = cssVar
    } else if (token.type === 'shadow') {
      boxShadow[token.path[token.path.length - 1]] = cssVar
    } else if (token.type === 'typography') {
      const name = token.path.slice(1).join('-')
      fontSize[name] = `var(--${token.path.join('-')}-font-size)`
    }
  }

  const config = {
    theme: {
      extend: {
        colors,
        spacing,
        borderRadius,
        boxShadow,
        fontSize
      }
    }
  }

  const lines = [
    '// Auto-generated by burooj.design/compile.mjs. Do not edit.',
    '// Source: tokens.json (DTCG format)',
    '',
    `export default ${JSON.stringify(config, null, 2)}`,
    ''
  ]

  return lines.join('\n')
}

function setNested(obj, path, value) {
  if (path.length === 1) {
    obj[path[0]] = value
    return
  }
  if (!obj[path[0]] || typeof obj[path[0]] !== 'object') {
    obj[path[0]] = {}
  }
  setNested(obj[path[0]], path.slice(1), value)
}

// ── Main ────────────────────────────────────────────────────────────────────

function main() {
  if (!existsSync(TOKENS_PATH)) {
    console.error(`Error: ${TOKENS_PATH} not found.`)
    process.exit(1)
  }

  const raw = readFileSync(TOKENS_PATH, 'utf-8')
  let tokensJson
  try {
    tokensJson = JSON.parse(raw)
  } catch (e) {
    console.error(`Error: tokens.json is not valid JSON: ${e.message}`)
    process.exit(1)
  }

  const tokens = walkTokens(tokensJson)
  console.log(`Parsed ${tokens.length} tokens from tokens.json`)

  mkdirSync(BUILD_DIR, { recursive: true })

  const css = generateCss(tokens)
  writeFileSync(join(BUILD_DIR, 'tokens.css'), css, 'utf-8')
  console.log(`  -> build/tokens.css (${css.length} bytes)`)

  const tailwind = generateTailwindConfig(tokens)
  writeFileSync(join(BUILD_DIR, 'tailwind.tokens.js'), tailwind, 'utf-8')
  console.log(`  -> build/tailwind.tokens.js (${tailwind.length} bytes)`)

  console.log('Done.')
}

main()
